# 使用基础镜像
FROM ubuntu:latest

# 安装Git工具
RUN apt-get update && apt-get install -y git

# 设置工作目录
WORKDIR /usr/src

# 克隆GitHub上的仓库
RUN git clone https://github.com/zhoubichuan/abstract-express.git /usr/src

# 全局安装依赖
RUN npm i -g nodemon typescript ts-node

COPY package.json ./package.json

# 安装依赖
RUN npm install

# 容器启动时执行的命令
CMD ["nodemon"]